name: docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Sphinx and Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-copybutton furo Jinja2

    - name: Build Documentation
      working-directory: docs
      run: |
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MANIMX }}
        publish_dir: ./docs/build/html
